"""instrument.py -- read a published vocabulary of norms, and find every site in the
system that publishes it at which one of those norms could be imposed.

Object: a PostgreSQL source tree.

  the vocabulary   src/backend/utils/errcodes.txt -- one SQLSTATE per line:
                   sqlstate <ws> E|W|S <ws> ERRCODE_MACRO [<ws> condition_name]
                   The fourth field is optional. Where it is absent the code gets no
                   PL/pgSQL condition name and no row in the manual's Appendix A.

  a site           a textual occurrence of the macro in the shipped tree, outside the
                   vocabulary file and outside everything derived from it.

Two rules count sites, deliberately of different widths, and both are reported:

  RULE A (narrow)  errcode( MACRO )  -- the canonical form by which the backend
                   attaches a SQLSTATE to an error it is raising. Whitespace and
                   newlines between the tokens are allowed; nothing else is.

  RULE B (wide)    the macro token anywhere in an implementation file, by word
                   boundary. Includes comparisons, switch labels, table entries and
                   direct assignments to a sqlerrcode field -- i.e. every way the
                   implementation can name the norm, whether to impose it or to
                   recognise it having been imposed by someone else.

Files are classified before either rule runs, and the classification is committed:

  vocabulary       src/backend/utils/errcodes.txt itself
  generated        any file declaring in its first three lines that it is
                   autogenerated from errcodes.txt -- these are the vocabulary
                   restated in another syntax, not sites
  doc              anything under doc/ -- prose, examples, prebuilt HTML
  translation      any .po/.pot file -- message catalogues
  implementation   everything else: the system itself

No file is excluded by name. The rule is a property of the file, and the counts under
each class are reported so a reader can disagree with the classification and re-derive.

Usage:  python3 instrument.py <tree-root> <out.json>
"""

import json
import os
import re
import sys

VOCAB_REL = os.path.join("src", "backend", "utils", "errcodes.txt")

# A code line: five SQLSTATE characters, the E/W/S kind, the macro, optional condition
CODE_RE = re.compile(
    r"^([0-9A-Z]{5})\s+([EWS])\s+(ERRCODE_[A-Z0-9_]+)\s*(\S+)?\s*$"
)
SECTION_RE = re.compile(r"^Section:\s*(.*)$")

GENERATED_MARK = "autogenerated from src/backend/utils/errcodes.txt"

# Extensions worth reading at all. Everything else in the tree is binary, build
# scaffolding or data, and is not searched. Recorded so the scope is auditable.
READ_EXT = {
    ".c", ".h", ".cpp", ".y", ".l", ".pl", ".pm", ".py", ".sql", ".sgml", ".xml",
    ".html", ".txt", ".po", ".pot", ".sh", ".in", ".m4", ".conf", ".sample",
    ".pgc", ".tcl", ".rb", ".java", ".php", ".spec", ".build", ".mk", ".ac",
}


def parse_vocabulary(path):
    """errcodes.txt -> ordered list of entries, each carrying the class it sits in."""
    entries = []
    section = None
    with open(path, encoding="utf-8") as fh:
        for lineno, raw in enumerate(fh, 1):
            line = raw.rstrip("\n")
            if not line.strip():
                continue
            if line.startswith("#"):
                m = SECTION_RE.match(line.lstrip("# ").strip())
                if m:
                    section = m.group(1).strip()
                continue
            m = SECTION_RE.match(line)
            if m:
                section = m.group(1).strip()
                continue
            m = CODE_RE.match(line)
            if m:
                sqlstate, kind, macro, condition = m.groups()
                entries.append({
                    "sqlstate": sqlstate,
                    "kind": kind,
                    "macro": macro,
                    "condition": condition,
                    "klass": sqlstate[:2],
                    "section": section,
                    "line": lineno,
                })
            else:
                raise ValueError("unparsed line %d: %r" % (lineno, line))
    return entries


def classify(rel, head):
    if rel == VOCAB_REL:
        return "vocabulary"
    if GENERATED_MARK in head:
        return "generated"
    if rel.split(os.sep)[0] == "doc":
        return "doc"
    if rel.endswith(".po") or rel.endswith(".pot"):
        return "translation"
    return "implementation"


def walk(root):
    """Yield (relpath, klass, text) for every readable text file carrying 'ERRCODE_'."""
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames.sort()
        for name in sorted(filenames):
            ext = os.path.splitext(name)[1].lower()
            if ext not in READ_EXT:
                continue
            full = os.path.join(dirpath, name)
            rel = os.path.relpath(full, root)
            try:
                with open(full, encoding="utf-8", errors="replace") as fh:
                    text = fh.read()
            except (OSError, UnicodeError):
                continue
            if "ERRCODE_" not in text:
                continue
            head = "\n".join(text.split("\n", 3)[:3])
            yield rel, classify(rel, head), text


def measure(root):
    vocab_path = os.path.join(root, VOCAB_REL)
    entries = parse_vocabulary(vocab_path)
    macros = [e["macro"] for e in entries]
    if len(set(macros)) != len(macros):
        raise ValueError("duplicate macro name in the vocabulary")

    # RULE A: errcode( MACRO ) -- one pass over each file, capturing the macro.
    rule_a = re.compile(r"errcode\s*\(\s*(ERRCODE_[A-Z0-9_]+)\s*\)")
    # RULE B: any macro token at word boundaries.
    rule_b = re.compile(r"\b(ERRCODE_[A-Z0-9_]+)\b")

    known = set(macros)
    counts = {m: {"A": 0, "B": 0, "doc": 0, "translation": 0, "generated": 0}
              for m in macros}
    files_by_class = {}
    # macros found in the tree that the vocabulary does not contain
    unknown = {}
    # per-macro: the implementation files that mention it (rule B), for reading later
    where = {m: [] for m in macros}

    for rel, klass, text in walk(root):
        files_by_class.setdefault(klass, []).append(rel)
        b_hits = rule_b.findall(text)
        if klass == "implementation":
            a_hits = rule_a.findall(text)
            for m in a_hits:
                if m in known:
                    counts[m]["A"] += 1
                else:
                    unknown.setdefault(m, {"A": 0, "B": 0, "files": []})["A"] += 1
            for m in b_hits:
                if m in known:
                    counts[m]["B"] += 1
                    if rel not in where[m]:
                        where[m].append(rel)
                else:
                    u = unknown.setdefault(m, {"A": 0, "B": 0, "files": []})
                    u["B"] += 1
                    if rel not in u["files"]:
                        u["files"].append(rel)
        elif klass in ("doc", "translation", "generated"):
            for m in b_hits:
                if m in known:
                    counts[m][klass] += 1
                else:
                    unknown.setdefault(m, {"A": 0, "B": 0, "files": []})
        # klass == "vocabulary": the vocabulary is not a site for itself

    rows = []
    for e in entries:
        m = e["macro"]
        c = counts[m]
        if c["A"] > 0:
            bucket = "1-raised"
        elif c["B"] > 0:
            bucket = "2-named-not-raised"
        elif c["doc"] > 0:
            bucket = "3-prose-only"
        else:
            bucket = "4-vocabulary-only"
        rows.append(dict(e, sites_a=c["A"], sites_b=c["B"], doc=c["doc"],
                         translation=c["translation"], generated=c["generated"],
                         bucket=bucket, files=where[m]))

    return {
        "root": os.path.basename(os.path.abspath(root)),
        "vocabulary_file": VOCAB_REL,
        "n_codes": len(rows),
        "file_classes": {k: len(v) for k, v in sorted(files_by_class.items())},
        "files": {k: sorted(v) for k, v in sorted(files_by_class.items())},
        "unknown_macros": unknown,
        "rows": rows,
    }


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    result = measure(sys.argv[1])
    with open(sys.argv[2], "w", encoding="utf-8") as fh:
        json.dump(result, fh, indent=1, sort_keys=True)
    print("%s: %d codes, files by class %s"
          % (result["root"], result["n_codes"], result["file_classes"]))
