"""interface_test.py -- test the instrument on a tree that is NOT the population.

F-084 (register 030): test an interface on data outside the population you are about
to predict over. The population is PostgreSQL **18.6**. This runs on **16.9**.

The seven checks below were written before this file was run once. Each prints only
what it needs to be judged. The full 16.9 measurement is written to a file and is NOT
printed, because 16.9's partition sizes would tell me 18.6's, and PREDICTIONS.md is
not closed yet. What that file contains is declared in PREDICTIONS.md and it is
committed, so a reader can check that nothing printed here reveals the buckets.

  IT1  the vocabulary parses: every non-comment line is a code line, every SQLSTATE is
       five characters, every kind is E/W/S, every macro is unique
  IT2  the file classification does what it claims: the vocabulary file is 'vocabulary'
       and every file declaring itself autogenerated is 'generated'
  IT3  rule A is a subset of rule B: sites_a <= sites_b for every macro, no exceptions
  IT4  rule A finds sites for three codes that cannot possibly lack them
  IT5  negative control: a macro name that is not in the tree gets zero under both rules
  IT6  macros the implementation names that the vocabulary does not contain -- printed,
       because if the instrument cannot see those it is not measuring what it claims
  IT7  a synthetic fixture with a hand-made answer: four codes, one per bucket, and the
       instrument must place all four correctly

Usage:  python3 interface_test.py <16.9-tree-root> <out.json>
"""

import json
import os
import re
import shutil
import sys
import tempfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import instrument  # noqa: E402

FIXTURE_VOCAB = """\
#
# a hand-made vocabulary, four codes, one per bucket
#
Section: Class ZZ - Fixture

ZZ000    E    ERRCODE_FIXTURE_RAISED             fixture_raised
ZZ001    E    ERRCODE_FIXTURE_NAMED_ONLY         fixture_named_only
ZZ002    W    ERRCODE_FIXTURE_PROSE_ONLY
ZZ003    E    ERRCODE_FIXTURE_ORPHAN             fixture_orphan
"""

FIXTURE_IMPL = """\
void f(void)
{
    ereport(ERROR,
            (errcode(ERRCODE_FIXTURE_RAISED),
             errmsg("raised here")));
    if (edata->sqlerrcode == ERRCODE_FIXTURE_NAMED_ONLY)
        recognise();
}
"""

FIXTURE_GENERATED = """\
/* autogenerated from src/backend/utils/errcodes.txt, do not edit */
#define ERRCODE_FIXTURE_RAISED 1
#define ERRCODE_FIXTURE_NAMED_ONLY 2
#define ERRCODE_FIXTURE_PROSE_ONLY 3
#define ERRCODE_FIXTURE_ORPHAN 4
"""

FIXTURE_DOC = """\
<para>For example, one may report ERRCODE_FIXTURE_PROSE_ONLY.</para>
"""


def build_fixture(base):
    """A tree with a known answer. Every path mirrors the real tree's shape."""
    os.makedirs(os.path.join(base, "src", "backend", "utils"))
    os.makedirs(os.path.join(base, "src", "backend", "commands"))
    os.makedirs(os.path.join(base, "src", "include", "utils"))
    os.makedirs(os.path.join(base, "doc", "src", "sgml"))
    w = lambda p, s: open(os.path.join(base, p), "w", encoding="utf-8").write(s)
    w(os.path.join("src", "backend", "utils", "errcodes.txt"), FIXTURE_VOCAB)
    w(os.path.join("src", "backend", "commands", "thing.c"), FIXTURE_IMPL)
    w(os.path.join("src", "include", "utils", "errcodes.h"), FIXTURE_GENERATED)
    w(os.path.join("doc", "src", "sgml", "xfunc.sgml"), FIXTURE_DOC)


def main(root, out):
    checks = []

    def check(cid, ok, detail):
        checks.append({"id": cid, "pass": bool(ok), "detail": detail})
        print("  %-4s %s  %s" % (cid, "PASS" if ok else "FAIL", detail))

    print("interface test -- instrument on PostgreSQL 16.9, outside the population")

    # --- IT7 first: the fixture, because if it fails nothing else means anything ---
    tmp = tempfile.mkdtemp(prefix="fixture-")
    try:
        build_fixture(tmp)
        fx = instrument.measure(tmp)
        got = {r["macro"]: r["bucket"] for r in fx["rows"]}
        want = {
            "ERRCODE_FIXTURE_RAISED": "1-raised",
            "ERRCODE_FIXTURE_NAMED_ONLY": "2-named-not-raised",
            "ERRCODE_FIXTURE_PROSE_ONLY": "3-prose-only",
            "ERRCODE_FIXTURE_ORPHAN": "4-vocabulary-only",
        }
        check("IT7", got == want, "fixture buckets %s" % json.dumps(got, sort_keys=True))
        fx_classes = fx["file_classes"]
        check("IT2", fx_classes.get("vocabulary") == 1
              and fx_classes.get("generated") == 1
              and fx_classes.get("doc") == 1
              and fx_classes.get("implementation") == 1,
              "fixture file classes %s" % json.dumps(fx_classes, sort_keys=True))
    finally:
        shutil.rmtree(tmp)

    # --- the real out-of-population tree ---
    res = instrument.measure(root)

    entries = instrument.parse_vocabulary(os.path.join(root, instrument.VOCAB_REL))
    macros = [e["macro"] for e in entries]
    kinds = sorted({e["kind"] for e in entries})
    widths = sorted({len(e["sqlstate"]) for e in entries})
    check("IT1", len(set(macros)) == len(macros) and kinds == ["E", "S", "W"]
          and widths == [5],
          "%d code lines, %d unique macros, kinds %s, sqlstate widths %s"
          % (len(macros), len(set(macros)), kinds, widths))

    real_classes = res["file_classes"]
    gen = res["files"].get("generated", [])
    check("IT2b", real_classes.get("vocabulary") == 1 and len(gen) >= 3,
          "file classes %s; generated: %s"
          % (json.dumps(real_classes, sort_keys=True), ", ".join(gen)))

    bad = [r["macro"] for r in res["rows"] if r["sites_a"] > r["sites_b"]]
    check("IT3", not bad, "%d macros with sites_a > sites_b" % len(bad))

    must = ["ERRCODE_SYNTAX_ERROR", "ERRCODE_UNDEFINED_TABLE",
            "ERRCODE_DIVISION_BY_ZERO"]
    by_macro = {r["macro"]: r for r in res["rows"]}
    have = {m: by_macro[m]["sites_a"] > 0 for m in must if m in by_macro}
    check("IT4", len(have) == 3 and all(have.values()),
          "rule A finds sites for %s" % json.dumps(have, sort_keys=True))

    absent = "ERRCODE_THIS_MACRO_IS_NOT_IN_ANY_POSTGRESQL_TREE"
    hits = 0
    for rel, klass, text in instrument.walk(root):
        hits += len(re.findall(r"\b%s\b" % absent, text))
    check("IT5", hits == 0, "negative control %s found %d times" % (absent, hits))

    unknown = sorted(res["unknown_macros"])
    check("IT6", True,
          "%d macro names in implementation files that the vocabulary does not "
          "contain: %s" % (len(unknown), ", ".join(unknown) if unknown else "(none)"))

    payload = {
        "purpose": "instrument test, F-084, on a tree outside the population",
        "tree": res["root"],
        "population": "postgresql-18.6",
        "checks": checks,
        "all_passed": all(c["pass"] for c in checks),
        "note": "the 16.9 measurement itself is in interface-measurement-16.9.json "
                "and was not read before PREDICTIONS.md closed",
    }
    with open(out, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, indent=1, sort_keys=True)

    side = os.path.join(os.path.dirname(out), "interface-measurement-16.9.json")
    with open(side, "w", encoding="utf-8") as fh:
        json.dump(res, fh, indent=1, sort_keys=True)

    print("\n%s -- %d checks, %d passed"
          % ("ALL PASS" if payload["all_passed"] else "FAILURES PRESENT",
             len(checks), sum(c["pass"] for c in checks)))
    return 0 if payload["all_passed"] else 1


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    sys.exit(main(sys.argv[1], sys.argv[2]))
